# Copyright 2024 General Atomics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[workspace]
name = "toksearch_d3d"
channels = ["ga-fdp", "conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.11"
fdp = ">=0.1.0"
ptdata = ">=2.0.2,<3"
toksearch = ">=2.7.1"
matplotlib = "*"
imas_composer = ">=0.2"
socat = ">=1.8.1.1,<2"
seaborn = ">=0.13.2,<0.14"
pelicanplatform = ">=7.24.3,<8"
anthropic = "0.101.*"
socksio = ">=1.0.0,<2"

[pypi-dependencies]
toksearch_d3d = { path = ".", editable = true }

[feature.docs.dependencies]
python = "3.10.*"
mkdocs = "1.5.3.*"
mkdocs-autorefs = "<1.4"
mkdocs-material = "9.5.*"
mkdocstrings = "0.24.1.*"
mkdocstrings-python = "1.9.1.*"
mkdocs-jupyter = "0.24.6.*"
mike = "2.0.*"
griffe = "<1"

[feature.docs.tasks]
docs-build = "mkdocs build"
docs-serve = "mkdocs serve"

[environments]
docs = { features = ["docs"], no-default-feature = true }
