[workspace]
name = "toksearch_smol_agent"
channels = ["ga-fdp", "conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12.*"
toksearch = "*"
toksearch_d3d = "*"
protobuf = "6.31.1.*"
pandas = "*"
ipython = "*"
pyyaml = "*"
pyzmq = "*"
matplotlib = "*"
numpy = "*"

[pypi-dependencies]
smolagents = "*"
litellm = "*"
